resources:
  repositories:
    - repository: devops
      type: github
      name: MobisysGmbh/devops-templates
      endpoint: MobisysGmbH
      ref: refs/heads/release/v6

trigger: none
pr: none

extends:
  template: /yaml/kickstarter-templates/package-pipeline.yml@devops
  parameters:
    targetFeed: mobisys-internal
    packageType: npm
    allowedPublishingBranches: refs/heads/master
    testSteps:
    - script: npm run test:js
      displayName: Run unit tests
